[server]
headless = true
address = "0.0.0.0"
port = 5000

[theme]
# Dark theme colors
primaryColor = "#FFDC3C"  # Bright yellow accent
backgroundColor = "#000000"  # Deep black
secondaryBackgroundColor = "#111111"  # Slightly lighter black for cards
textColor = "#FFFFFF"  # White text
font = "sans-serif"

[deprecation]
showPyplotGlobalUse = false